# Generated by Django 5.1.6 on 2025-03-02 15:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('category', models.CharField(choices=[('policy', 'School Policies'), ('form', 'Forms'), ('curriculum', 'Curriculum'), ('newsletter', 'Newsletters'), ('other', 'Other')], default='other', max_length=20)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
