# Generated by Django 5.1.6 on 2025-03-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('policy', 'Школьная политика'), ('form', 'Учителям'), ('curriculum', 'Учебный план'), ('newsletter', 'Newsletters'), ('other', 'Другое')], default='other', max_length=20),
        ),
    ]
