# Generated by Django 5.1.6 on 2025-03-21 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0003_alter_document_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faculty',
            new_name='Teacher',
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
    ]
