# Generated by Django 5.1.6 on 2025-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0006_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='www.subject'),
        ),
    ]
