# Generated by Django 5.1.6 on 2025-04-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0007_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='www.subject'),
        ),
    ]
