# Generated by Django 5.1.6 on 2025-04-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_lesson_subject_alter_lesson_teacher'),
        ('www', '0008_alter_teacher_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='schedule.subject'),
        ),
    ]
