# Generated by Django 5.1.6 on 2025-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0009_delete_subject_alter_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='additional',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='awards',
            field=models.TextField(blank=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Квалификационная категория'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.TextField(blank=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.CharField(blank=True, max_length=50, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='reception_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name='Часы приема'),
        ),
    ]
