# Generated by Django 5.1.6 on 2025-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0012_newsimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-date_sent'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'События', 'verbose_name_plural': 'События'},
        ),
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='admin_response',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ администратора'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В обработке'), ('completed', 'Завершена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='date_sent',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
    ]
