# Generated by Django 5.1.6 on 2025-05-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_lesson_subject_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Номер класса', 'verbose_name_plural': 'Номер класса'},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Учебный кабинет', 'verbose_name_plural': 'Учебные кабинеты'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписание'},
        ),
        migrations.AlterModelOptions(
            name='replacement',
            options={'verbose_name': 'Замена', 'verbose_name_plural': 'Замена'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
